### ISSUE TITLE
Current View Name Always Displayed

### ISSUE THREAD

**Issue by shaunandrews** [lonnieezell/Ocular-Template-Library#10]
I may be missing a config, but the Current View is always displayed at the top of the page:

Lines 233 through 239 of application/libraries/Template.php:
        // Grab our current view name, based on controller/method
        // which routes to views/controller/method.
        if (empty($this->current_view))
        {
            $this->current_view = $this->ci->router->directory . $this->ci->router->class . '/' . $this->ci->router->method;
            echo 'Current View = '. $this->current_view;
        }

I couldn't find any way to turn this off, other than commenting out the echo statement.

**Comment by lonnieezell** [comment]
No, you're correct. That is a left over line from some debugging I was doing that I missed. Commenting it out is the correct method. :) I'll have that fixed in the repo soon.
