### ISSUE TITLE
AJAX Layout Not Working

### ISSUE THREAD

**Issue by shaunandrews** [lonnieezell/Ocular-Template-Library#11]
For some reason, I have to add "layouts/" to my config/template.php file:

$config['OCU_ajax_layout'] = 'layouts/ajax';

Without it, I keep getting 500 server errors.

May have something to do with closed Issue #2 (http://github.com/lonnieezell/Ocular-Template-Library/issues/closed/#issue/2)

**Comment by lonnieezell** [comment]
Looks like the problem was on line 226, where it's assigning the value to $layout. Unlike for the standard layout, I was not including the layout folder in the call. I've fixed it on my machine and it will be uploaded here in a bit.
