### ISSUE TITLE
viewing not in the right way...

### ISSUE THREAD

**Issue by ghost** [lonnieezell/Ocular-Template-Library#3]
i have this this action in Welcome controller:
    function index() {
        $this->template->render();
    }
i create 1 view ('view/welcome/index.php') and the content is <h1>Test</h1>
when i run the web, the index view not render in <?php echo $this->template->yield(); ?> block.
# i got this:

<h1>Test</h1>

<html>
<head><title><?php echo $site_name ?></title></head>
<body>

<p>Page rendered in {elapsed_time} seconds using {memory_usage}.</p>

</body>
</html>

**Comment by lonnieezell** [comment]
It's hard to say without knowing your exact setup. I've got the current version working without an issue on several sites. Depending on how recent your version is, there was an error that might have caused that, but I can't be sure. Don't think I've ever gotten a blank screen, I've always gotten some type of error or another.
