### ISSUE TITLE
Controllers in sub-folders

### ISSUE THREAD

**Issue by alertmybanjos** [lonnieezell/Ocular-Template-Library#6]
When controllers are organized into sub-folders, the Template->render function should look in sub-folders for views too (mentioned as a future to-do on the old website).

I think it's as simple as adding the router->directory to line 236, like so:

```
$this->current_view = $this->ci->router->directory . $this->ci->router->class . '/' . $this->ci->router->method;
```

**Comment by lonnieezell** [comment]
You're correct that it's not currently working. I've been setting the current view manually by doing $this->ocular->current_view = '...'; lately but have never gotten around to fixing that. I'll try to look into it soon.
