### ISSUE TITLE
Pass array directly to template->set

### ISSUE THREAD

**Issue by kenzik** [lonnieezell/Ocular-Template-Library#7]
I've modified Template.php to check if the $var_name is an array, and if so, walk it to set the key/vals on this->data.

This makes it easier to migrate an existing site that is using CI's standard $data way to Ocular.

Would be nice to have this implemented so future versions don't need to be patched.

**Comment by kenzik** [comment]
```
public function set($var_name='', $value='') 
{
    $this->_mark('Template_Set_start');

    if (empty($var_name))
    {
        return false;
    }

    // Added by dkenzik
    // 20101001
    // Easier migration when $data is scaterred all over your project
    //
    if(is_array($var_name) && $value=='')
    {
        foreach($var_name as $key => $value)
        {
        $this->data[$key] = $value;
        }           
    }
    else
    {
        $this->data[$var_name] = $value;
    }

    $this->_mark('Template_Set_end');
}
```

**Comment by lonnieezell** [comment]
Well, my bad. I've had that code implemented for one of my projects, but it never made it back to the official code. I'll put yours in there.
